language: cpp

sudo: false
os: linux
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-6
    - zlib1g-dev

install:
  # Build mrustc
 - CC=gcc-6 CXX=g++-6 make

# Tests! (check that they parse, and keep going)
script:
# libstd
 - make rustc-nightly/
 - make output/libstd.hir TAIL_COUNT=2
# rustc (not the actual binary, because that doesn't emit a file yet)
 - make output/librustc_driver.hir TAIL_COUNT=2
# Tests
# - make rust_tests-run-pass RUST_TESTS_FINAL_STAGE=expand -k
