language: cpp
install: make libboost-dev libboost-iostreams-dev

sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
 - eval "${MATRIX_EVAL}"
before_script:
 - make UPDATE

script:
 - make
# - make test
 - make rust_tests-run-pass
