language: cpp

sudo: false
os: linux
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-6
    - zlib1g-dev

install:
  # Build mrustc
 - CC=gcc-6 && CXX=g++-6 make
#  # Build libstd (and hello world). Also downloads the source
# - make test
#  # Create the test dependencies testlibstd (and hello world). Also downloads the source
# - make test_deps_run-pass.mk

# Tests! (check that they parse, and keep going)
script:
 - make test
# - make rust_tests-run-pass RUST_TESTS_FINAL_STAGE=expand -k
