language: cpp

sudo: false
os: linux
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-6
    - zlib1g-dev

install:
  # Build mrustc
 - CC=gcc-6 CXX=g++-6 make

# Tests! (check that they parse, and keep going)
script:
 - make test TAIL_COUNT=2
 - make output/librustc_typeck.hir output/librustc_mir.hir output/librustc_trans.hir output/libsyntax_ext.hir TAIL_COUNT=2
# - make rust_tests-run-pass RUST_TESTS_FINAL_STAGE=expand -k
