language: cpp

sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - debian-sid
          packages:
            - g++-6
            - zlib1g-dev
            - libssl1.0.0
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - debian-sid
          packages:
            - g++-5
            - zlib1g-dev
            - libssl1.0.0
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
 - eval "${MATRIX_EVAL}"

script:
 - make
 - make test
# - make rust_tests-run-pass RUST_TESTS_FINAL_STAGE=parse
