language: cpp

sudo: false
os: linux
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
  packages:
    - g++-6
    - zlib1g-dev
    - cmake cmake-data

install:
 # Build mrustc
 - make RUSTCSRC
 - CC=gcc-6 CXX=g++-6 make

script:
# libstd and hello_world
 - CC=gcc-6 make test TAIL_COUNT=2
# rustc
# - CC=gcc-6 make output/rustc TAIL_COUNT=15
# Tests
 - CC=gcc-6 make local_tests -k
 - CC=gcc-6 make rust_tests -k
